name: Challenge
on: push
jobs:
  geral:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Deploy
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
